version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.json-server
    ports:
      - '3001:3001'
    volumes:
      - .:/app
