# Используем официальный образ Node.js в качестве базового
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json в рабочую директорию
COPY package*.json ./

# Устанавливаем только необходимые зависимости
RUN npm install json-server

# Копируем базу данных
COPY db.json /app/db.json

# Открываем порт 3001
EXPOSE 3001

# Запускаем JSON Server
CMD ["npx", "json-server", "--watch", "db.json", "--port", "3001"]
